spring:
  application:
    name: order-service
  jpa:
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

payment-service:
  url: http://localhost:8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
